const frame=document.getElementById('game'),out=document.getElementById('output'),button=document.getElementById('run');
frame.onload=()=>out.textContent='Ready';
button.onclick=async()=>{
  const g=frame.contentWindow.__bloodwake,doc=frame.contentDocument,lines=[];if(!g){out.textContent='FAIL: game did not boot';return;}
  const original=JSON.stringify(g.save),persisted=localStorage.getItem('bloodwake.save.v1');g.sound.enabled=false;button.disabled=true;
  function assert(ok,message){if(!ok)throw Error(message);}
  function test(name,fn){try{g.start();fn();lines.push('PASS '+name);}catch(e){lines.push('FAIL '+name+': '+e.message);}out.textContent=lines.join('\n');}
  function step(seconds){for(let i=0;i<Math.ceil(seconds*60);i++)g.update(1/60);}
  function clearEnemies(){for(const e of g.enemies)g.entities.remove(e.mesh);g.enemies=[];g.boss=null;g.spawnClock=999;}
  test('WASD movement and arena bounds',()=>{clearEnemies();g.keys.add('KeyD');step(1);g.keys.clear();assert(g.hunter.position.x>6&&g.hunter.position.x<7,'D should move ~6.4m');g.hunter.position.set(27.4,0,12);g.keys.add('KeyD');step(1);assert(g.hunter.position.x<=27.5,'escaped arena');});
  test('Gravestone collision stops traversal',()=>{clearEnemies();const o=g.obstacles.find(o=>o.x===-10);g.hunter.position.set(o.x-3,0,o.z);g.keys.add('KeyD');step(.6);assert(g.hunter.position.x<=o.x-o.r-.44,'walked through gravestone');});
  test('Aimed silver bullets kill a real enemy',()=>{clearEnemies();g.camera.position.set(0,26,19);g.camera.lookAt(0,0,0);g.camera.updateMatrixWorld();g.pointer.set(0,.4);const e=g.spawnEnemy('ghoul',0,-5);e.speed=0;g.mouseDown=true;step(1);assert(g.fired>=4,'shoot input failed');assert(g.kills===1,'projectiles did not kill');assert(g.gems.length>0,'kill did not drop XP');});
  test('XP pickup pauses for 3 unique upgrades; selection resumes',()=>{clearEnemies();g.dropGem(0,0,12);step(.1);assert(g.state==='upgrade','XP did not trigger level');assert(doc.querySelectorAll('[data-choice]').length===3,'missing 3 UI choices');assert(new Set(g.pendingChoices.map(u=>u.id)).size===3,'duplicate choices');doc.querySelector('[data-choice="0"]').click();assert(g.state==='playing'&&g.upgradesChosen===1,'upgrade did not resume');});
  test('Dash has cooldown and invulnerability',()=>{clearEnemies();g.keys.add('KeyD');g.dash();const hp=g.hp;g.hurt(20);assert(g.hp===hp,'dash invulnerability failed');g.dash();assert(g.dashesUsed===1,'cooldown bypass');step(.2);assert(g.hunter.position.x>5,'dash did not move');});
  test('Nova damages multiple enemies and obeys cooldown',()=>{clearEnemies();g.spawnEnemy('ghoul',2,0);g.spawnEnemy('ghoul',-2,0);g.nova();assert(g.kills===2,'AoE did not kill both enemies');g.nova();assert(g.novasUsed===1,'nova cooldown bypass');});
  test('Pause freezes timer, damage, movement and spawns',()=>{g.pause();const s=g.snapshot();g.keys.add('KeyD');step(3);g.hurt(20);assert(g.time===s.time&&g.hp===s.hp&&g.hunter.position.x===s.position.x,'simulation changed while paused');g.resume();assert(g.state==='playing','resume failed');});
  test('Death, rewards, retry and persistent purchase',()=>{clearEnemies();g.kills=80;g.time=120;g.invuln=0;g.hurt(999);assert(g.state==='defeat','death missing');assert(doc.querySelector('#retry'),'result UI missing');assert(g.save.souls>=16,'earned currency missing');doc.querySelector('#back-menu').click();doc.querySelector('#open-legacy').click();const buy=doc.querySelector('[data-buy="power"]'),old=g.save.ranks.power;buy.click();assert(g.save.ranks.power===old+1,'purchase failed');assert(JSON.parse(localStorage.getItem('bloodwake.save.v1')).ranks.power===old+1,'purchase not saved');doc.querySelector('#legacy-back').click();doc.querySelector('#start').click();assert(g.hp===g.stats.maxHp&&g.time===0&&g.kills===0,'retry not reset');assert(g.stats.damage>22,'permanent power not applied');});
  test('60-second boss spawns and telegraphed shockwave damages',()=>{clearEnemies();g.time=59.99;g.nextBoss=60;step(.1);assert(g.boss?.type==='boss','boss absent');const b=g.boss;b.mesh.position.set(2,0,0);b.speed=0;b.attack=0;g.invuln=0;const hp=g.hp;step(.7);assert(g.rings.some(r=>r.hostile),'shockwave absent');assert(g.hp<hp,'shockwave did not damage');});
  test('300 seconds produces victory and only one settlement',()=>{clearEnemies();const runs=g.save.runs;g.time=299.99;step(.1);assert(g.state==='victory','no victory');assert(doc.querySelector('h2').textContent==='血 月 獵 場','menu DOM missing');assert(doc.querySelector('#dialog-content h2').textContent==='血月落幕','victory UI absent');assert(g.save.runs===runs+1,'settlement missing');g.finish(true);assert(g.save.runs===runs+1,'settled twice');});
  test('Crowd simulation remains finite and bounded',()=>{clearEnemies();g.hp=10000;g.stats.maxHp=10000;for(let i=0;i<90;i++){const a=i*2.399;g.spawnEnemy(i%3===0?'bat':i%5===0?'brute':'ghoul',Math.cos(a)*18,Math.sin(a)*18);}step(5);assert(g.enemies.length<=90,'enemy cap exceeded');assert(g.enemies.every(e=>Number.isFinite(e.mesh.position.x)&&Number.isFinite(e.mesh.position.z)),'nonfinite crowd position');g.renderer.render(g.scene,g.camera);assert(g.renderer.info.render.calls<2600,'excessive draw calls');lines.push(`INFO crowd draw calls: ${g.renderer.info.render.calls}`);});
  Object.assign(g.save,JSON.parse(original));if(persisted===null)localStorage.removeItem('bloodwake.save.v1');else localStorage.setItem('bloodwake.save.v1',persisted);g.toMenu();button.disabled=false;out.textContent=lines.join('\n')+`\n${lines.filter(x=>x.startsWith('PASS')).length} passed, ${lines.filter(x=>x.startsWith('FAIL')).length} failed`;
};
